### ISSUE TITLE
Test Liveness of Touchscreen

### ISSUE THREAD

**Issue by wecodewithmichaelmccloskey** [wecodewithmichaelmccloskey/Smart_Breadboard#22]
- [ ] What happens when the lcd is powered on?
- [ ] Get example file from library running

**Comment by wecodewithmichaelmccloskey** [comment]
When the display is powered on, with no instructions, it simply shows a blank white screen:


![Image](https://user-images.githubusercontent.com/114356709/219982175-8da93b46-c128-42e9-9804-291c155beed3.jpg)

**Comment by wecodewithmichaelmccloskey** [comment]
Attempted to use the Adafruit CircuitPython RGB Display module. However, when I try to run the example file I get the error
`OSError: /dev/spidev0.0 does not exist`

I also cannot find the spidev module when I run the `lsmod | grep spi` even after enabling SPI using `raspi-config` and rebooting. 

To solve this issue, I attempted to download spidev using `sudo apt install python3-spidev` which returns `python3-spidev is already the newest version (20200602~200721-1).`
I also used `pip3 install spidev` which returns `Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (3.5)`
Neither resolved the issue.

I attempted to get spidev from github using the following commands:
`git clone https://github.com/doceme/py-spidev.git`
`cd py-spidev`
`make`
`sudo make install`
(which also required me to use `sudo apt-get install python3-setuptools` to be able to `make`)
This also did not resolve the issue.

I will be going into office hours on Wednesday, Thursday, and Friday to try to get SPI and the Adafruit CircuitPython RGB Display module working so that I can confirm the functionality of the display.

**Comment by ffund** [comment]
> Attempted to use the Adafruit CircuitPython RGB Display module. However, when I try to run the example file I get the error `OSError: /dev/spidev0.0 does not exist`
> 
> I also cannot find the spidev module when I run the `lsmod | grep spi` even after enabling SPI using `raspi-config` and rebooting.

Since the error message indicates that the OS cannot find the SPI device, it's possible that the SPI peripheral on your Pi is broken. (For example, if you accidentally connected it to a 5V SPI bus, or if there is a soldering problem on the display header that causes a short.)

My recommendation is to first validate if this is the case:

* borrow a Pi from another member of your team
* put your SD card in that Pi (the activation of the SPI driver by `raspi-config` is on the SD card, not on the Pi, so if you have done that on your SD card then the SPI peripheral should be active when you put your SD card into a different Pi.)
* try running that example code (which again, is on your SD card!). Don't even connect the display - just see if it gets past the "finding and opening the SPI device at 0,0" step, or if it raises the same error.

If it raises the same error: it's probably an OS/driver/configuration problem..
If it does not raise the error about finding the SPI 0,0 device: it's probably your Pi.

If it turns out that SPI0 on your Pi is broken, you can put your SD card back into your own Pi, and try SPI1 to see if it works.  You can enable SPI1 by adding a line to the boot config file, then rebooting the Pi, as described [here](https://pinout.xyz/pinout/spi).

After rebooting, check in `/dev` and check the output of `lsmod` to see if the SPI device is recognized.

If SPI1 is also not recognized, there might be more damage to the Pi than we can overcome by working around it - then we'd probably have to swap out the Pi.

Regardless: before trying to connect the display again, you should make sure you are not connecting it in a way that can damage the SPI bus it is connected to.
 
> To solve this issue, I attempted to download spidev using `sudo apt install python3-spidev` which returns `python3-spidev is already the newest version (20200602~200721-1).` I also used `pip3 install spidev` which returns `Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (3.5)` Neither resolved the issue.
> 
> I attempted to get spidev from github using the following commands: `git clone https://github.com/doceme/py-spidev.git` `cd py-spidev` `make` `sudo make install` (which also required me to use `sudo apt-get install python3-setuptools` to be able to `make`) This also did not resolve the issue.

There is no indication that the Python library is the problem - if the driver is not even loaded and the SPI0 device does not appear in `/dev`, that's several steps below the Python library.

**Comment by wecodewithmichaelmccloskey** [comment]
After placing my sd card into Fatiha's Pi, the same error still occurred.

**Comment by wecodewithmichaelmccloskey** [comment]
Using the Adafruit CircuitPython RGB Display module now I get the error
```
pi@raspberrypi23:~/touchscreen $ python3 display_image.py
Traceback (most recent call last):
  File "/home/pi/touchscreen/display_image.py", line 89, in <module>
    image = image.resize((scaled_width, scaled_height), Image.Resampling.BICUBIC)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 62, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'PIL.Image' has no attribute 'Resampling'
```

The output on the display looks like this:


![Image](https://user-images.githubusercontent.com/114356709/220720392-afbf7f25-83ab-47a9-b851-1343b4e1498b.jpg)

**Comment by wecodewithmichaelmccloskey** [comment]
I was successfully able to test the liveness of the touchscreen by running two example files. The output of the first example file:


![Image](https://user-images.githubusercontent.com/114356709/221380801-57a5228f-7292-4415-8238-6ead39f08c9f.jpg)


The output of the second example file:


![Image](https://user-images.githubusercontent.com/114356709/221380810-e4d22946-8875-47ab-92bf-b2f962ef8a50.jpg)

**Comment by wecodewithmichaelmccloskey** [comment]
@creechelseaa please review
